local ls = require("luasnip")
local s = ls.snippet
local i = ls.insert_node
local t = ls.text_node
local fmt = require("luasnip.extras.fmt").fmt
return {
  s("UnionFind", {
    t({
      "struct UnionFind {",
      "    parent: Vec<usize>,",
      "    rank: Vec<usize>,",
      "}",
      "",
      "impl UnionFind {",
      "    fn new(n: usize) -> Self {",
      "        UnionFind {",
      "            parent: (0..n).collect(),",
      "            rank: vec![0; n],",
      "        }",
      "    }",
      "",
      "    fn root(&mut self, x: usize) -> usize {",
      "        if self.parent[x] == x {",
      "            return x;",
      "        }",
      "        self.parent[x] = self.root(self.parent[x]);",
      "        self.parent[x]",
      "    }",
      "",
      "    fn is_same(&mut self, x: usize, y: usize) -> bool {",
      "        self.root(x) == self.root(y)",
      "    }",
      "",
      "    fn unite(&mut self, mut parent: usize, mut child: usize) -> bool {",
      "        parent = self.root(parent);",
      "        child = self.root(child);",
      "        if parent == child {",
      "            return false;",
      "        }",
      "",
      "        if self.rank[parent] < self.rank[child] {",
      "            std::mem::swap(&mut parent, &mut child);",
      "        }",
      "",
      "        self.parent[child] = parent;",
      "        self.rank[parent] += self.rank[child];",
      "        true",
      "    }",
      "",
      "    fn size(&mut self, x: usize) -> usize {",
      "        let root = self.root(x);",
      "        self.rank[root]",
      "    }",
      "}",
    }),
    i(0),
  }),

  s("UnionFind2d", {
    t({
      "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
      "struct Node2d {",
      "    r: usize,",
      "    c: usize,",
      "}",
      "impl Node2d {",
      "    fn new(r: usize, c: usize) -> Self {",
      "        Self { r, c }",
      "    }",
      "    fn r(&self) -> usize {",
      "        self.r",
      "    }",
      "    fn c(&self) -> usize {",
      "        self.c",
      "    }",
      "}",
      "",
      "struct UnionFind2d {",
      "    parent: Vec<Vec<Node2d>>,",
      "    size: Vec<Vec<usize>>,",
      "}",
      "",
      "impl UnionFind2d {",
      "    fn new(height: usize, width: usize) -> Self {",
      "        let mut parent = vec![vec![Node2d::new(0, 0); width]; height];",
      "        for r in 0..height {",
      "            for c in 0..width {",
      "                parent[r][c] = Node2d::new(r, c);",
      "            }",
      "        }",
      "        UnionFind2d {",
      "            parent,",
      "            size: vec![vec![1; width]; height],",
      "        }",
      "    }",
      "",
      "    fn parent(&self, node: Node2d) -> Node2d {",
      "        let r = node.r();",
      "        let c = node.c();",
      "        self.parent[r][c]",
      "    }",
      "",
      "    fn size_at(&self, node: Node2d) -> usize {",
      "        self.size[node.r()][node.c()]",
      "    }",
      "",
      "    fn set_parent(&mut self, old: Node2d, new: Node2d) {",
      "        self.parent[old.r()][old.c()] = new;",
      "    }",
      "",
      "    fn set_size(&mut self, node: Node2d, value: usize) {",
      "        self.size[node.r()][node.c()] = value;",
      "    }",
      "",
      "    fn root(&mut self, node: Node2d) -> Node2d {",
      "        if self.parent(node) == node {",
      "            return node;",
      "        }",
      "        let new_parent = self.root(self.parent(node));",
      "        self.set_parent(node, new_parent);",
      "        self.parent(node)",
      "    }",
      "",
      "    fn is_same(&mut self, node1: Node2d, node2: Node2d) -> bool {",
      "        self.root(node1) == self.root(node2)",
      "    }",
      "",
      "    fn unite(&mut self, mut parent: Node2d, mut child: Node2d) -> bool {",
      "        parent = self.root(parent);",
      "        child = self.root(child);",
      "        if parent == child {",
      "            return false;",
      "        }",
      "",
      "        if self.size_at(parent) < self.size_at(child) {",
      "            std::mem::swap(&mut parent, &mut child);",
      "        }",
      "",
      "        self.set_parent(child, parent);",
      "        let new_size = self.size_at(parent) + self.size_at(child);",
      "        self.set_size(parent, new_size);",
      "        self.set_size(child, 0);",
      "        true",
      "    }",
      "",
      "    fn size(&mut self, node: Node2d) -> usize {",
      "        let root = self.root(node);",
      "        self.size_at(root)",
      "    }",
      "}",
    }),
    i(0),
  }),
}
